language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: odHjFhU2rq1WvfULodCS2hX73z5Dpbec4urL85pyhA3vaEK2ZKqDgMJF+svXaLB/+3ClhLat8SoO6+HKrwbTU67mCjDH0+IMksnSClLTvlH/ZiFg6HhBNlRoE3uMOKRXztaQkX1BloRATg2GZ2FHFNToDxumopF0w2yi6p1YuAHfjYFcRkFuMT3dswdAwJAYGXJ0UmpkwudA+OE3mBDbW8ehXwS04FqglKZ8WLfwECxOjQMgevbFZW/s9YZm52KBpQHfRBS8/XnzcurbA2qbR0E6ZRtYIFlHipJgPnVxCKS8bJquVAB1Re4sPyfFz8Xr1YeBHX1ep2W+pUfhO2o6+eaF+UUZ8c2NLdoeq0CrXBRlQ72obCLvK9xkESAq1Ms388SQLpyl7bhDgqk/fXwPaY9s2u/90T379MENnHzZfl79LZrQVICRh+FT//IyKcIm+cB9M/0h/m4APiegp0jw41KJJYOv9Dk/H4+SmaHZaZCW8sKLlvh/ycO+gy9t+reF9C7f+/hixTnUpp6gEM/lZEd3vZE1ARNWcray0XMnPQRXxVeaIexBF3IilBQeZBGLyC4l9jieQ6twP9OddDrpKgGPTUVFum1jsPa0BZoGjXtaBIRT8DMzRXXJMnoOcHYUfpSwGjdHpPQtX26Nar8QSvmEw30TMSfH2567u/YY6GE=
  - secure: bykvs/TqGljV0eCq2s03pTpjHfv534hyhAlISGkqqGbMW5kvqTo6cdbiIYiUsHnYgSDisuoiM0PyrrkrpNYxWuy152kjRSTyGvqGC5X/85hQR62qdGGhzvAizLNtH/TUyVV+5AEzwupW5U3oh0Qd4KavY7Aj7jLBBs+5a0cyqxDjrdptCxs5Gu3Kh7VL7nMXjwUDFH/8nLdOXyZ5cGKe7ivVuA6JZs8BSngVfC877mbK3DjpLrZ7cSIRFGMfwdojysWyxs/+qRgB+vEYS0XR43XXPe+Ff9ZAeRELYpy6vrtIa2BtKeaCuKe16ueCLyYvAC+rGHb816Vkke20z++DfNIA+bXgw/XObqxrp1bO+kS3MJHzjngC9FELiY8ja3xn8eFpjTxl9WLqOjL53uF5uewJOXCaJY/o0FOWpmBRa1yGGqR5p0HFyzYs7VUyE5Noj6QZPB1PMgcW5MdSng5W71UP5Q914yFJCgsVfhV2C2t788VrBnHZr0rd+6J89cmfwTVuln5ta0KbGnW7mz2effv6sNRjHWIlAZ/mxqKFVUkuLTkQSQniKTl+9KizLeucGke4Dx0x8rHgz1oKe/v37pXsHZknOgj45GivigZz4AJfkEGW0Kzt5Id2fKZgE8Dy3VI5mVRmNp2sgSKz/Q6gAYfTWcOnnZGSzSyQOTSf6wA=
  - secure: mK3N5RrhjnAspzOM7PjJ61kbpSjX7gWWGEcD174TRtY9Itty5CfDhpn7igPXnyG4kR3Qb3vF1UCAcao+whHW/+L19wxSReXAu2kgqTuwCcpkN3s3rtRzsErYjfgl1LYeFSc4Q/4tT3TfafKwcfGqIA9DtuU+NTU8ghi56MzyEuHExsL24X2YezA3clSq1ftWWiZdpPqHhx0kxGGJB4aKOBZunuQSNBM2MkpD78ea0hJuwOYCCXloDH11AwyanfTNWaWDcMInhyig+xGQ64ZrvkO56kRxRRrNhCcCJhx40T0EZBmsM67OpGJXv2rjF0JEgT/3fpKunZSS9fMe6BlTXB9RGJorP8dcDeyGpYnlOps6q12yzu8aGwhmaNav9RLEd6AayuijAohAA+YsvnDCxgIIv97TP3Q9Pdj+aOSZOLziRzzr+Sw8AA7e0H4VsoaW3WWCKNhDXeWLzxRpzNT95/wDCxOVU37QG3M6k4Zyne55tr1PPWsNwf2jcDNpI2AJqtLiyMNUVlMmvYc2ayw3eV1FPjM0HwF24pzKnMLEBueLo4Ge92PZQNxcLcaqM8F1tcB/bnzgNb1fjxQmAkZRK2umIu/tMsSv9sm/MIUIIPeu/sFD7Dyg1sjKxJB1Lxki30tZz3xu2qlSKCkyn9KZJzCPOMyR8Ft0f1JphC49e28=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_75d13685da3e_key -iv $encrypted_75d13685da3e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: dseJO6OFImfTvVbYMgWnydkoD2fOlHPrcmadFBLhWy9n/QB0FR6QfBzzcaCkqe3rlae/PVjvCqhlWJTP6dge72kOjohRFCPW2rDAuetX6kXY+a0RKuAvF/4YvhoMKcHx2VlN9TmUFlnrxnM6c/xLH0zNV6B43c5FWo2U8jYS7x4zbsjXGSYaG5fcs3/x9Cxs5LWMBW74y65PvSbwS/ui8xNJM1FmPSfEH0M9iVc5dVFx+zY0yungZVsl+hqy2cGvloa7GD3ZY0PIp8LnRapIULXXFwEm5w9xaoK2xo7r/7owNESW/19hhwUd3A23qqNbmXvihfffb3KCXE48mrE88Wktf41N+NxhqlrWNubQu2WWneuj9bfFs5t20rvG7jQAi6HJB0oioM//0+DVwjg1InogSh/tC2YJKqnslAZsEVcKRXDXIKuXXsy/AKw8WaC57g1a73VwIJ8u194pgwuUSEpK7mwmr7HAxLsruorbhT0QUY3O4g/zeMvlTUGv7CzEKmWFVhgHEjPs4eaQ0RJdtNngyxM0N1YuoZVIkLhxYn3ZW1HuIC9tC6plwVyNZzLXJPbz0U0tvtk7lwC+gL3twgVYEbtq8D2nMsnYBHUiP8NsatvCeJxdeqvt903RFk8rs/dv1scNeN6mpXzvBKJrYqypqFj9skv0u4R1+90jyiI=
